---
- hosts:  all
  become: true  # Perform the following tasks as "sudo".
  vars_files:
    - vars/apache.yml
    - vars/app.yml
  roles:
    - apt
    - git
    - apache
    - mariadb
    - php
    - app
